/**
 * Canonical error codes used throughout the application.
 * Every AppError carries one of these codes so the client can react precisely.
 */
export enum ErrorCode {
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  CONFLICT = "CONFLICT",
  AI_ANALYSIS_FAILED = "AI_ANALYSIS_FAILED",
  AI_ANALYSIS_TIMEOUT = "AI_ANALYSIS_TIMEOUT",
  FILE_PROCESSING_FAILED = "FILE_PROCESSING_FAILED",
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  // ai-analysis domain codes
  ANALYSIS_NOT_FOUND = "ANALYSIS_NOT_FOUND",
  ANALYSIS_NOT_COMPLETED = "ANALYSIS_NOT_COMPLETED",
  ANALYSIS_IN_PROGRESS = "ANALYSIS_IN_PROGRESS",
  INVALID_SCORE_RANGE = "INVALID_SCORE_RANGE",
}
